// <auto-generated />
using System;
using BackendApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251208113306_AddKebabasTable")]
    partial class AddKebabasTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendApi.Models.Kebabas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("integer");

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("double precision");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Fats")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double>("Proteins")
                        .HasColumnType("double precision");

                    b.Property<string>("Sauce")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Size")
                        .HasColumnType("integer");

                    b.Property<bool>("Spicy")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Kebabas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 600,
                            Carbohydrates = 70.0,
                            Category = "Chicken",
                            Description = "A delicious classic chicken kebab with garlic sauce.",
                            Fats = 20.0,
                            Name = "Classic Kebab",
                            Price = 5.9900000000000002,
                            Proteins = 30.0,
                            Sauce = "Garlic",
                            Size = 1,
                            Spicy = false
                        },
                        new
                        {
                            Id = 2,
                            Calories = 700,
                            Carbohydrates = 60.0,
                            Category = "Beef",
                            Description = "A fiery beef kebab for those who love spice.",
                            Fats = 25.0,
                            Name = "Spicy Beef Kebab",
                            Price = 6.4900000000000002,
                            Proteins = 40.0,
                            Sauce = "Spicy",
                            Size = 0,
                            Spicy = true
                        },
                        new
                        {
                            Id = 3,
                            Calories = 500,
                            Carbohydrates = 80.0,
                            Category = "Vegetarian",
                            Description = "A healthy and tasty vegetarian kebab with yogurt sauce.",
                            Fats = 10.0,
                            Name = "Vegetarian Kebab",
                            Price = 5.4900000000000002,
                            Proteins = 15.0,
                            Sauce = "Yogurt",
                            Size = 1,
                            Spicy = false
                        });
                });

            modelBuilder.Entity("BackendApi.Models.Kebabine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<double>("XCoordinate")
                        .HasColumnType("double precision");

                    b.Property<double>("YCoordinate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Kebabines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Vilniaus g. 10",
                            City = "Vilnius",
                            Email = "info@jammi.lt",
                            EmployeeCount = 5,
                            Name = "Jammi Kebabai",
                            OpeningHours = "10:00 - 22:00",
                            PhoneNumber = "+37060000001",
                            Rating = 4.5,
                            XCoordinate = 54.687199999999997,
                            YCoordinate = 25.279699999999998
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kauno g. 5",
                            City = "Kaunas",
                            Email = "info@kebabinn.lt",
                            EmployeeCount = 3,
                            Name = "Kebab Inn",
                            OpeningHours = "11:00 - 23:00",
                            PhoneNumber = "+37060000002",
                            Rating = 4.2000000000000002,
                            XCoordinate = 54.898499999999999,
                            YCoordinate = 23.903600000000001
                        },
                        new
                        {
                            Id = 3,
                            Address = "Taikos pr. 15",
                            City = "Klaipėda",
                            Email = "info@liuks.lt",
                            EmployeeCount = 4,
                            Name = "Liuks Kebabai",
                            OpeningHours = "09:00 - 00:00",
                            PhoneNumber = "+37060000003",
                            Rating = 4.7999999999999998,
                            XCoordinate = 55.703299999999999,
                            YCoordinate = 21.144300000000001
                        });
                });

            modelBuilder.Entity("BackendApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BackendApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrdersCount")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackendApi.Models.Order", b =>
                {
                    b.HasOne("BackendApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
